### ISSUE TITLE
Problem running "Cannot call method 'replace' of undefined"

### ISSUE THREAD

**Issue by marcellodesales** [jakeleboeuf/contributor#10]
Hi there,

I just installed it... 
```
mdesales@ubuntu [08/09/201521:42:12] ~/dev/github/intuit/istanbul-cobertura-badger (release/1.0.0 *) $ sudo npm install contributor -g
[sudo] password for mdesales: 
npm WARN engine contributor@0.1.25: wanted: {"node":"0.10.x","npm":"1.4.x"} (current: {"node":"0.10.40","npm":"2.13.0"})
/usr/bin/contributor -> /usr/lib/node_modules/contributor/bin/contributor
contributor@0.1.25 /usr/lib/node_modules/contributor
├── yesno@0.0.1
├── ansi-color@0.2.1
├── github@0.2.4 (mime@1.3.4)
├── request@2.51.0 (caseless@0.8.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, http-signature@0.10.1, form-data@0.2.0, tough-cookie@2.0.0, bl@0.9.4, hawk@1.1.1)
└── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.6, winston@0.8.3, utile@0.2.1)
```

And I command failed executing in a public repository...

```
mdesales@ubuntu [08/09/201521:42:42] ~/dev/github/intuit/istanbul-cobertura-badger (release/1.0.0 *) $ contributor

/usr/lib/node_modules/contributor/lib/contributor.js:52
  repo: contribApi[4].replace('.git', '')
                      ^
TypeError: Cannot call method 'replace' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/contributor/lib/contributor.js:52:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/contributor/bin/contributor:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Is this a bug? Anything I did wrong?

thanks
Marcello

**Comment by jakeleboeuf** [comment]
Hey there Marcello - so sorry you're having trouble! Are you certain your `package.json` has a valid `repository` field? That needs to be formatted to follow [npmjs.com guidelines](https://docs.npmjs.com/files/package.json#repository).

I should be catching these errors, but have not had the time to maintain this project for several months. Let me know how that goes!

**Comment by marcellodesales** [comment]
Hi @jakeleboeuf 

The current value is as follows: https://github.com/intuit/node-pom-parser/blob/master/package.json#L29-L32

```js
 "repository": {
    "type": "git",
    "url": "git@github.com:marcellodesales/node-pom-parser.git"
  },
```

The only thing that's wrong is that the organization still has my username instead of the current location... Anything else?

**Comment by stramel** [comment]
@marcellodesales The repository URL should be something like `https://github.com/marcellodesales/node-pom-parser.git`.

If you view the [source code](https://github.com/jakeleboeuf/contributor/blob/master/src/lib/contributor.js#L29-L52) it is doing a split on the URL with "/" and referencing spots 3 & 4. This would only be correct using the "http" version. 

@jakeleboeuf An enchancement may be to handle different URLs. 

```js
  if(!pack.repository.url) {

    console.log(color('No Repository url found in your package.json.', 'red+bold'));
    console.log(color('See the npm docs for formatting info: https://www.npmjs.org/doc/json.html#repository', 'magenta'));

    // Jankfully kill the process
    process.kill();
    return;
  } else {
    contribApi = pack.repository.url.split(/(\/|:)/);
  }
}


// *****************************
// Contributor Module + Defaults
// *****************************
var contribApiLen = contribApi.length;
var contributor = module.exports = {
  complete: 0,
  totalCommits: 0,
  totalCommitsArray: [],
  username: contribApi[contribApiLen -2],
  password: null,
  repo: contribApi[contribApiLen -1].replace('.git', '')
};
```

**Comment by marcellodesales** [comment]
@stramel I will try that... thanks!

**Comment by marcellodesales** [comment]
@jakeleboeuf @stramel Is there a way to generate the update automatically? For automatic CI, I'd like travis to do run "contributors"... The current implementation asks the user for questions:

```
$ contributor 
✔ Saved a backup as .package.json
✔ Contributors added to your package.json from Github
Save to contributors.md? (yes/no) yes
✔ Contributors added to your contributors.md as:
###### Contributors
[Marcello de Sales](https://github.com/marcellodesales)
<font color="#999">41 Commits</font> / <font color="#6cc644">2445++</font> / <font color="#bd3c00"> 1385--</font>
<font color="#dedede">100.00%&nbsp;<font color="#dedede">|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||</font><font color="#f4f4f4"></font><br><br>
###### [Generated](https://github.com/jakeleboeuf/contributor) on Wed Sep 02 2015 16:59:50 GMT-0700 (PDT)
✔ All done
```

I'd like to have a default flag that automatically updates the current contributors file, so that I can use other libraries to automatically generate a new commit if the file is different...

**Comment by stramel** [comment]
@marcellodesales You are wanting the `interactive: false` flag as requested in #7
